ARG PYTHON_VERSION

FROM $PYTHON_VERSION

# Set the timezone
ENV TZ=Asia/Kolkata

WORKDIR /app

COPY ./src/requirements.txt /app/requirements.txt

RUN python -m pip install --upgrade pip

RUN pip install --no-cache-dir --upgrade -r requirements.txt

RUN pip install debugpy

# Install cron
# RUN apt update && apt install -y cron && apt install -y supervisor && apt install -y curl
RUN apt update && apt install -y supervisor && apt install -y curl

# Copy the Supervisor configuration file
COPY ./src/extras/supervisord.local /etc/supervisor/conf.d/supervisord.conf

# Start supervisor service
# CMD python -m debugpy --wait-for-client --listen 0.0.0.0:5000 -m uvicorn main:app --reload --host 0.0.0.0

CMD supervisord -n